[package]
name = "ourchat"
version = "0.1.0"
entrypoint = "src/lib.typ"
authors = ["QuadnucYard", "WenSimEHRP"]
license = "MIT"
description = "Forge wonderful chat messages"
categories = ["fun"]
keywords = ["chat", "message"]
repository = "https://github.com/QuadnucYard/ourchat-typ"
exclude = ["examples"]
