[package]
name = "ourchat-extended"
version = "0.1.0"
entrypoint = "src/lib.typ"
authors = ["WenSimEHRP", "QuadnucYard"]
license = "MIT"
description = "Forge more chat messages"
categories = ["fun"]
keywords = ["chat", "message"]
repository = "https://github.com/WenSimEHRP/ourchat-extended"
exclude = ["examples"]
